server:
  port: ${PORT:5001}
spring:
    application:
        name: simple-spring-cors
    security:
        user:
            name: admin
            password: password
logging:
  level:
    org:
      springframework:
        security: ${LOG_LEVEL:INFO}
        web: ${LOG_LEVEL:INFO}